name: effective_mobile_task
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: 4.9.0
  freezed_annotation: 2.4.1
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.8.0
  freezed: 2.4.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
